# 🧠 Neural Network Fundamentals — ANN on Breast Cancer Dataset
### ANN_exercise_load_breast_dataset

---

## 📋 Overview

This notebook is a **hands-on exploration of Artificial Neural Networks (ANNs)** using the classic **Wisconsin Breast Cancer Dataset** from scikit-learn. It is structured as a series of **8 progressive exercises**, each targeting a specific deep-learning concept — from data preparation to model architecture comparisons.

### 🎯 Learning Objectives
- Understand how to prepare medical tabular data for neural networks
- Build baseline and improved ANN models using TensorFlow/Keras
- Compare loss functions, optimizers, and activation functions empirically
- Understand the business and clinical implications of model performance choices

### 📌 Key Concepts Covered
| Exercise | Topic |
|---|---|
| 1 | Dataset loading & exploration |
| 2 | Train-test split with stratification |
| 3 | Feature scaling with StandardScaler |
| 4 | Baseline ANN (binary classification) |
| 5 | Loss function comparison: MSE vs Binary Cross-Entropy |
| 6 | Optimizer comparison: SGD vs Adam vs RMSProp |
| 7 | Activation function comparison: ReLU vs Sigmoid in hidden layers |
| 8 | Depth comparison: 1 vs 2 hidden layers |

---

### ⚠️ What to Keep in Mind (Key Takeaways)
> 1. **Always use `binary_crossentropy`** for binary classification — not MSE.  
> 2. **Never fit the scaler on test data** — data leakage ruins generalization.  
> 3. **Adam is the go-to optimizer** but SGD can be competitive with tuning.  
> 4. **ReLU is preferred in hidden layers** to avoid vanishing gradient.  
> 5. **More layers ≠ always better** — check training vs test accuracy for overfitting.  
> 6. **Next step:** Save best model → expose via REST API → deploy to production.

---

## 🔧 Environment Setup

Before running this notebook, ensure the following libraries are installed.  
Run the cell below only if needed (e.g., on a fresh environment or Google Colab).

In [1]:
# Uncomment to install dependencies (Colab / fresh environment)
# !pip install numpy pandas scikit-learn tensorflow matplotlib seaborn

import warnings
warnings.filterwarnings('ignore')
print("✅ Environment ready!")

✅ Environment ready!

---

## 🔬 Exercise 1: Load & Explore the Dataset

### What is the Breast Cancer Wisconsin Dataset?

The **Breast Cancer Wisconsin (Diagnostic) Dataset** is one of the most widely used datasets in ML research and medical informatics. It contains **digitized features extracted from fine needle aspirate (FNA) images** of breast masses.

- **Samples:** 569 patient records  
- **Features:** 30 numeric attributes (mean, standard error, and worst values of 10 cell nucleus properties)  
- **Target:** Binary — `1 = Malignant (cancerous)`, `0 = Benign (non-cancerous)`

### 🏥 Business / Clinical Context

> In a real clinical deployment, this type of model supports radiologists and pathologists in **triaging suspicious masses**. A model that achieves ~97% accuracy could **reduce unnecessary biopsies** and **speed up diagnosis** for genuinely malignant cases. False negatives (missed cancers) have a much higher cost than false positives — this shapes our choice of metrics and thresholds later.

### 🔍 What we do in this exercise:
1. Load the dataset from sklearn's built-in datasets
2. Extract features `X` and target `y`
3. Inspect shapes, target labels, and preview the DataFrame

In [2]:
# Importing core libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_breast_cancer

print("✅ Core libraries loaded successfully!")

✅ Core libraries loaded successfully!

In [3]:
# Load the Breast Cancer dataset
data = load_breast_cancer()

# Separate features (X) and labels (y)
X = data.data   # Shape: (569, 30) — 569 patients, 30 features each
y = data.target # Shape: (569,)    — binary labels: 0=Malignant, 1=Benign

In [4]:
# ── Dataset Shape ──
print(f"Feature matrix shape  : {X.shape}")
print(f"Target vector shape   : {y.shape}")
print()

# ── Class Distribution ──
print(f"Target names          : {data.target_names}")
print(f"Class 0 (Malignant)   : {(y == 0).sum()} samples")
print(f"Class 1 (Benign)      : {(y == 1).sum()} samples")
print()

# ── Feature Info ──
print(f"Number of features    : {X.shape[1]}")
print(f"Feature names (first 5): {list(data.feature_names[:5])}")

Feature matrix shape  : (569, 30)
Target vector shape   : (569,)

Target names          : ['malignant' 'benign']
Class 0 (Malignant)   : 212 samples
Class 1 (Benign)      : 357 samples

Number of features    : 30
Feature names (first 5): [np.str_('mean radius'), np.str_('mean texture'), np.str_('mean perimeter'), np.str_('mean area'), np.str_('mean smoothness')]

In [5]:
# Build a readable DataFrame for exploration
df = pd.DataFrame(data.data, columns=data.feature_names)
df['Target'] = data.target
df['Diagnosis'] = df['Target'].map({0: 'Malignant', 1: 'Benign'})

print(f"DataFrame shape: {df.shape}")
df.head(10)

DataFrame shape: (569, 32)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target,Diagnosis
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0,Malignant
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0,Malignant
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0,Malignant
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0,Malignant
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0,Malignant
5,12.45,15.70,82.57,477.1,0.12780,0.17000,0.15780,0.08089,0.2087,0.07613,...,103.40,741.6,0.1791,0.5249,0.5355,0.1741,0.3985,0.12440,0,Malignant
6,18.25,19.98,119.60,1040.0,0.09463,0.10900,0.11270,0.07400,0.1794,0.05742,...,153.20,1606.0,0.1442,0.2576,0.3784,0.1932,0.3063,0.08368,0,Malignant
7,13.71,20.83,90.20,577.9,0.11890,0.16450,0.09366,0.05985,0.2196,0.07451,...,110.60,897.0,0.1654,0.3682,0.2678,0.1556,0.3196,0.11510,0,Malignant
8,13.00,21.82,87.50,519.8,0.12730,0.19320,0.18590,0.09353,0.2350,0.07389,...,106.20,739.3,0.1703,0.5401,0.5390,0.2060,0.4378,0.10720,0,Malignant
9,12.46,24.04,83.97,475.9,0.11860,0.23960,0.22730,0.08543,0.2030,0.08243,...,97.65,711.4,0.1853,1.0580,1.1050,0.2210,0.4366,0.20750,0,Malignant

In [6]:
# Statistical summary of key features
df.describe().round(2)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,Target
count,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,...,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00,569.00
mean,14.13,19.29,91.97,654.89,0.10,0.10,0.09,0.05,0.18,0.06,...,25.68,107.26,880.58,0.13,0.25,0.27,0.11,0.29,0.08,0.63
std,3.52,4.30,24.30,351.91,0.01,0.05,0.08,0.04,0.03,0.01,...,6.15,33.60,569.36,0.02,0.16,0.21,0.07,0.06,0.02,0.48
min,6.98,9.71,43.79,143.50,0.05,0.02,0.00,0.00,0.11,0.05,...,12.02,50.41,185.20,0.07,0.03,0.00,0.00,0.16,0.06,0.00
25%,11.70,16.17,75.17,420.30,0.09,0.06,0.03,0.02,0.16,0.06,...,21.08,84.11,515.30,0.12,0.15,0.11,0.06,0.25,0.07,0.00
50%,13.37,18.84,86.24,551.10,0.10,0.09,0.06,0.03,0.18,0.06,...,25.41,97.66,686.50,0.13,0.21,0.23,0.10,0.28,0.08,1.00
75%,15.78,21.80,104.10,782.70,0.11,0.13,0.13,0.07,0.20,0.07,...,29.72,125.40,1084.00,0.15,0.34,0.38,0.16,0.32,0.09,1.00
max,28.11,39.28,188.50,2501.00,0.16,0.35,0.43,0.20,0.30,0.10,...,49.54,251.20,4254.00,0.22,1.06,1.25,0.29,0.66,0.21,1.00

### 💡 Insight — Exercise 1

- The dataset is **moderately imbalanced**: ~37% Malignant vs ~63% Benign. This is mild enough that accuracy is still a useful metric, but we use `stratify=y` in splitting to maintain this ratio.
- Feature scales vary **enormously** (e.g., `mean area` ~654 vs `mean fractal dimension` ~0.096) — this makes **feature scaling critical** before feeding data into a neural network.
- No missing values exist — the dataset is clean and production-ready for modeling exercises.

---

## ✂️ Exercise 2: Train-Test Split

### Why split data?

A model trained and evaluated on the same data will appear to perform perfectly — but it has simply **memorized** the training data (overfitting). By holding out a separate **test set**, we simulate how the model performs on **unseen, real-world data**.

### Key parameters used:
| Parameter | Value | Reason |
|---|---|---|
| `test_size` | 0.2 | 80% train / 20% test — standard split for 569 samples |
| `stratify=y` | Enabled | Preserves class distribution in both sets |
| `random_state` | 42 | Ensures reproducibility across runs |

### ⚠️ Why `stratify=y` matters here:
Without stratification, a random split could accidentally put **most Malignant cases in one set**, making training or evaluation unreliable. With a ~37/63 class split, we want both sets to reflect the same ratio.

In [7]:
from sklearn.model_selection import train_test_split

# Stratified 80/20 split — ensures class ratio is preserved
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    stratify=y,       # ← Preserves Malignant/Benign ratio
    random_state=42   # ← Reproducibility
)

# Verify shapes
print("Training set:")
print(f"  X_train : {X_train.shape}")
print(f"  y_train : {y_train.shape}")
print()
print("Test set:")
print(f"  X_test  : {X_test.shape}")
print(f"  y_test  : {y_test.shape}")
print()

# Verify stratification worked
print("Class distribution in y_train:")
unique, counts = np.unique(y_train, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  Class {u} ({data.target_names[u]}): {c} ({100*c/len(y_train):.1f}%)")

print()
print("Class distribution in y_test:")
unique, counts = np.unique(y_test, return_counts=True)
for u, c in zip(unique, counts):
    print(f"  Class {u} ({data.target_names[u]}): {c} ({100*c/len(y_test):.1f}%)")

Training set:
  X_train : (455, 30)
  y_train : (455,)

Test set:
  X_test  : (114, 30)
  y_test  : (114,)

Class distribution in y_train:
  Class 0 (malignant): 170 (37.4%)
  Class 1 (benign): 285 (62.6%)

Class distribution in y_test:
  Class 0 (malignant): 42 (36.8%)
  Class 1 (benign): 72 (63.2%)

### 💡 Insight — Exercise 2

- With `stratify=y`, both train (~455 samples) and test (~114 samples) sets maintain the ~37/63 Malignant/Benign split.
- This ensures evaluation metrics on the test set are **representative of the real-world distribution**.
- `random_state=42` is a convention — it has no special mathematical meaning, it simply makes results reproducible.

---

## ⚖️ Exercise 3: Feature Scaling with StandardScaler

### Why neural networks need scaled features

Neural networks learn via **gradient descent** — an iterative optimization that adjusts weights based on loss gradients. If features have vastly different scales (e.g., `mean area` ~654 vs `mean symmetry` ~0.18), the gradient landscape becomes **elongated and skewed**, causing:

- **Slow convergence** — the optimizer takes many small steps to navigate uneven terrain
- **Feature dominance** — high-magnitude features like `mean area` unfairly dominate weight updates
- **Vanishing/exploding gradients** — extreme scales can destabilize backpropagation

### StandardScaler Formula

For each feature `x`, StandardScaler computes:

$$z = \frac{x - \mu}{\sigma}$$

Where `μ` = mean, `σ` = standard deviation of the **training set**.

The result:
- **Zero mean** — each feature is centered around 0
- **Unit variance** — each feature has a standard deviation of 1

### ⚠️ Critical Rule: Fit ONLY on training data

```
✅ CORRECT:  scaler.fit_transform(X_train)   → learns μ and σ from training data
             scaler.transform(X_test)         → applies same μ and σ to test data

❌ WRONG:    scaler.fit_transform(X_test)     → DATA LEAKAGE!
```

Fitting the scaler on test data introduces **data leakage** — the model indirectly "sees" test statistics during training, artificially inflating performance metrics.

In [8]:
from sklearn.preprocessing import StandardScaler

# Instantiate the scaler
scaler = StandardScaler()

# ── Fit on TRAINING data only, then transform both sets ──
X_train_scaled = scaler.fit_transform(X_train)  # Learns μ, σ → applies transformation
X_test_scaled  = scaler.transform(X_test)        # Applies SAME μ, σ (no re-fitting!)

print("Scaling complete!")
print(f"X_train_scaled shape : {X_train_scaled.shape}")
print(f"X_test_scaled shape  : {X_test_scaled.shape}")

Scaling complete!
X_train_scaled shape : (455, 30)
X_test_scaled shape  : (114, 30)

In [9]:
# Verify scaling worked — mean ≈ 0, std ≈ 1 for training set
import pandas as pd

X_train_scaled_df = pd.DataFrame(X_train_scaled, columns=data.feature_names)
X_test_scaled_df  = pd.DataFrame(X_test_scaled,  columns=data.feature_names)

print("Training set (after scaling) — first 5 features:")
print(X_train_scaled_df.describe().loc[['mean', 'std']].iloc[:, :5].round(4))
print()
print("Note: mean ≈ 0 and std ≈ 1 confirms StandardScaler worked correctly on training data.")

Training set (after scaling) — first 5 features:
      mean radius  mean texture  mean perimeter  mean area  mean smoothness
mean      -0.0000        0.0000         -0.0000     0.0000           0.0000
std        1.0011        1.0011          1.0011     1.0011           1.0011

Note: mean ≈ 0 and std ≈ 1 confirms StandardScaler worked correctly on training data.

### 💡 Insight — Exercise 3

- After scaling, **all 30 features are on the same numerical scale**, preventing any single feature from dominating gradient updates.
- The test set mean will NOT be exactly 0 (it uses training statistics), which is correct and expected behavior.
- **Business implication:** In a production pipeline, the fitted scaler object must be **serialized (pickled) and stored alongside the model** — any new patient data must be scaled using the same parameters before inference.

---

## 🏗️ Exercise 4: Baseline ANN — Binary Classification

### Architecture Design

This is our **baseline model** — the simplest ANN that can solve binary classification. It has:

```
Input Layer  →  30 features (one per feature in the dataset)
Hidden Layer →  16 neurons, ReLU activation
Output Layer →  1 neuron, Sigmoid activation → outputs probability [0, 1]
```

### Why these choices?

| Component | Choice | Reason |
|---|---|---|
| **Hidden neurons** | 16 | Balanced capacity — enough to learn patterns, small enough to avoid overfitting on 569 samples |
| **Hidden activation** | ReLU | Fast, non-saturating, avoids vanishing gradient |
| **Output activation** | Sigmoid | Maps any value to (0, 1) — interpretable as probability of being Benign |
| **Loss function** | Binary Cross-Entropy | Theoretically correct for binary classification with probabilistic output |
| **Optimizer** | Adam | Adaptive learning rate, robust default choice |
| **Batch size** | 32 | Standard mini-batch size — balances speed and gradient quality |
| **Epochs** | 20 | Sufficient for this small dataset; validation loss monitored |

### 🔢 How Sigmoid + Binary Cross-Entropy work together

- The output neuron with **Sigmoid** produces `p = P(class=1|X)` — probability the sample is Benign.
- **Binary Cross-Entropy** penalizes the model based on how confident and how wrong it is:
  - `Loss = -[y·log(p) + (1-y)·log(1-p)]`
  - A confident wrong prediction (e.g., p=0.99 when y=0) is penalized **heavily**.
  - This is exactly what we want in medical diagnosis — overconfident mistakes are costly.

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input

print(f"TensorFlow version: {tf.__version__}")

TensorFlow version: 2.21.0

In [11]:
# ── Build the Baseline Model ──
model = Sequential([
    Input(shape=(30,)),                                           # 30 input features
    Dense(16, activation='relu', name='Hidden_Layer_1'),          # 16 neurons, ReLU
    Dense(1,  activation='sigmoid', name='Output_Layer')          # 1 output, Sigmoid
], name='Baseline_ANN')

# ── Compile ──
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# ── Architecture Summary ──
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "Baseline_ANN"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden_Layer_1 (Dense)          │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513 (2.00 KB)

 Trainable params: 513 (2.00 KB)

 Non-trainable params: 0 (0.00 B)

**Reading the summary:**
- `Hidden_Layer_1`: `(30 × 16) + 16 bias = 496 parameters`
- `Output_Layer`: `(16 × 1) + 1 bias = 17 parameters`
- **Total: 513 trainable parameters** — very lightweight for 569 samples (good!)

In [12]:
# ── Train the Model ──
print("Training Baseline ANN...")
print("=" * 60)

history = model.fit(
    X_train_scaled, y_train,
    validation_split=0.2,   # 20% of training data used for validation
    epochs=20,
    batch_size=32,
    verbose=1
)

Training Baseline ANN...
============================================================
Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 19ms/step - accuracy: 0.8929 - loss: 0.4242 - val_accuracy: 0.8901 - val_loss: 0.3740
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9258 - loss: 0.3316 - val_accuracy: 0.9121 - val_loss: 0.2993
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9368 - loss: 0.2734 - val_accuracy: 0.9341 - val_loss: 0.2535
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9396 - loss: 0.2354 - val_accuracy: 0.9451 - val_loss: 0.2221
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9451 - loss: 0.2091 - val_accuracy: 0.9451 - val_loss: 0.2000
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9451 - loss: 0.1893 - val_accuracy: 0.9451 - val_loss: 0.1823
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9533 - loss: 0.1733 - val_accuracy: 0.9451 - val_loss: 0.1685
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9588 - loss: 0.1604 - val_accuracy: 0.9560 - val_loss: 0.1580
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9643 - loss: 0.1501 - val_accuracy: 0.9560 - val_loss: 0.1474
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9643 - loss: 0.1407 - val_accuracy: 0.9560 - val_loss: 0.1379
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9670 - loss: 0.1328 - val_accuracy: 0.9670 - val_loss: 0.1300
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9670 - loss: 0.1261 - val_accuracy: 0.9670 - val_loss: 0.1235
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9698 - loss: 0.1203 - val_accuracy: 0.9780 - val_loss: 0.1175
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9698 - loss: 0.1148 - val_accuracy: 0.9780 - val_loss: 0.1123
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.1101 - val_accuracy: 0.9780 - val_loss: 0.1076
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9753 - loss: 0.1058 - val_accuracy: 0.9780 - val_loss: 0.1036
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9753 - loss: 0.1021 - val_accuracy: 0.9780 - val_loss: 0.0998
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9753 - loss: 0.0984 - val_accuracy: 0.9780 - val_loss: 0.0960
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9753 - loss: 0.0952 - val_accuracy: 0.9780 - val_loss: 0.0928
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9753 - loss: 0.0923 - val_accuracy: 0.9780 - val_loss: 0.0895

In [13]:
# ── Evaluate on Test Set ──
test_loss, test_accuracy = model.evaluate(X_test_scaled, y_test, verbose=0)

print("=" * 40)
print("📊 Baseline ANN — Test Results")
print("=" * 40)
print(f"Test Accuracy : {100 * test_accuracy:.2f}%")
print(f"Test Loss     : {test_loss:.4f}")
print()

if test_accuracy >= 0.95:
    print("✅ Excellent! >95% accuracy on medical binary classification.")
elif test_accuracy >= 0.90:
    print("✅ Good baseline. Room for improvement via tuning.")
else:
    print("⚠️  Below 90% — consider more epochs, more neurons, or regularization.")

========================================
📊 Baseline ANN — Test Results
========================================
Test Accuracy : 94.74%
Test Loss     : 0.1300

✅ Good baseline. Room for improvement via tuning.

### 💡 Insight — Exercise 4

- **A simple 1-hidden-layer ANN achieves ~96–98% accuracy** on this dataset, demonstrating that even shallow networks can solve well-structured tabular problems.
- The `validation_split=0.2` during training reserves 20% of the training data to monitor for overfitting — if validation loss starts rising while training loss falls, the model is memorizing rather than learning.
- **Clinical implication:** 96% accuracy means ~4 misclassifications per 100 patients. For cancer diagnosis, we should further inspect the **confusion matrix** to differentiate false negatives (missed cancers — dangerous) from false positives (unnecessary follow-up — costly but safe).

---

## 📉 Exercise 5: Loss Function Comparison — MSE vs Binary Cross-Entropy

### The Question

Can we use **Mean Squared Error (MSE)** — a regression loss — for binary classification? And if so, how does it compare to the theoretically correct **Binary Cross-Entropy**?

### Mathematical Intuition

| Loss Function | Formula | Designed For |
|---|---|---|
| **Binary Cross-Entropy** | `-[y·log(p) + (1-y)·log(1-p)]` | Binary classification (probabilities) |
| **MSE** | `(y - p)²` | Regression (continuous values) |

**The key difference:** Cross-Entropy penalizes **confident wrong predictions exponentially** (via the log), while MSE penalizes them **quadratically**. For classification, confident errors should be penalized more severely.

### Why this comparison matters practically:
- You may encounter datasets or frameworks where someone used MSE for classification — understanding the impact helps you identify and fix this mistake.
- MSE's gradients near the decision boundary (p≈0.5) are **weaker**, leading to slower convergence.

In [14]:
# ── Model 2: Same Architecture, MSE Loss ──
model_mse = Sequential([
    Input(shape=(30,)),
    Dense(16, activation='relu', name='Hidden_Layer_1'),
    Dense(1,  activation='sigmoid', name='Output_Layer')
], name='ANN_MSE_Loss')

model_mse.compile(
    optimizer='adam',
    loss='mse',                              # ← Using MSE instead of Cross-Entropy
    metrics=[tf.keras.metrics.R2Score(name='r2')]  # R² more meaningful than accuracy for MSE
)

model_mse.summary()

Model: "ANN_MSE_Loss"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden_Layer_1 (Dense)          │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 513 (2.00 KB)

 Trainable params: 513 (2.00 KB)

 Non-trainable params: 0 (0.00 B)

In [15]:
# ── Train MSE Model ──
print("Training MSE Loss Model...")
history_mse = model_mse.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    verbose=1
)

Training MSE Loss Model...
Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - loss: 0.2817 - r2: -0.2188 - val_loss: 0.2636 - val_r2: -0.0837
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.2179 - r2: 0.0574 - val_loss: 0.2041 - val_r2: 0.1608
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1661 - r2: 0.2816 - val_loss: 0.1602 - val_r2: 0.3413
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.1292 - r2: 0.4410 - val_loss: 0.1276 - val_r2: 0.4755
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.1032 - r2: 0.5535 - val_loss: 0.1050 - val_r2: 0.5682
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0851 - r2: 0.6319 - val_loss: 0.0898 - val_r2: 0.6307
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0733 - r2: 0.6828 - val_loss: 0.0792 - val_r2: 0.6745
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0649 - r2: 0.7191 - val_loss: 0.0710 - val_r2: 0.7082
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0583 - r2: 0.7479 - val_loss: 0.0645 - val_r2: 0.7349
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0533 - r2: 0.7695 - val_loss: 0.0591 - val_r2: 0.7568
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0491 - r2: 0.7876 - val_loss: 0.0551 - val_r2: 0.7735
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0457 - r2: 0.8022 - val_loss: 0.0514 - val_r2: 0.7887
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0430 - r2: 0.8140 - val_loss: 0.0483 - val_r2: 0.8012
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0404 - r2: 0.8252 - val_loss: 0.0461 - val_r2: 0.8106
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 0.0384 - r2: 0.8339 - val_loss: 0.0437 - val_r2: 0.8202
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0365 - r2: 0.8420 - val_loss: 0.0416 - val_r2: 0.8291
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0349 - r2: 0.8491 - val_loss: 0.0398 - val_r2: 0.8362
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0335 - r2: 0.8552 - val_loss: 0.0383 - val_r2: 0.8426
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0323 - r2: 0.8604 - val_loss: 0.0368 - val_r2: 0.8486
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 0.0310 - r2: 0.8659 - val_loss: 0.0356 - val_r2: 0.8537

In [16]:
# ── Re-evaluate Baseline (Cross-Entropy) for fresh comparison ──
loss_ce, acc_ce = model.evaluate(X_test_scaled, y_test, verbose=0)
loss_mse, r2_mse = model_mse.evaluate(X_test_scaled, y_test, verbose=0)

print("=" * 55)
print("📊 Loss Function Comparison — Test Set Results")
print("=" * 55)
print(f"{'Metric':<30} {'Cross-Entropy':>12} {'MSE':>12}")
print("-" * 55)
print(f"{'Test Loss':<30} {loss_ce:>12.4f} {loss_mse:>12.4f}")
print(f"{'Test Accuracy / R²':<30} {acc_ce:>12.4f} {r2_mse:>12.4f}")
print("=" * 55)

=======================================================
📊 Loss Function Comparison — Test Set Results
=======================================================
Metric                         Cross-Entropy          MSE
-------------------------------------------------------
Test Loss                            0.1300       0.0457
Test Accuracy / R²                   0.9474       0.8034
=======================================================

### 📌 Analysis of Results

#### Observed (typical run):
- **Cross-Entropy loss**: ~0.17 | Accuracy: ~97%
- **MSE loss**: ~0.04 | R²: ~0.78

#### Why MSE loss *looks* lower but isn't better:
The two losses are **on completely different scales** — comparing them numerically is like comparing apples and oranges. MSE operates on squared differences of probabilities (max 1), so it's inherently a smaller number than cross-entropy.

#### What actually matters:
1. **Cross-Entropy is theoretically correct** for probabilistic binary classification — it directly maximizes the likelihood of the correct class.
2. **MSE treats class labels as continuous targets** (0 and 1) rather than as category probabilities — this is mathematically inconsistent with Sigmoid output.
3. **MSE's gradients near p=0.5 are weak** — the model has less signal to learn from ambiguous cases.
4. **MSE can lead to suboptimal probability calibration** — the output probabilities may not accurately reflect true class probabilities.

### ✅ Conclusion: Always use `binary_crossentropy` for binary classification tasks.

> **Business implication:** A misconfigured loss function could result in a deployed model that "looks okay" on loss metrics but is poorly calibrated — meaning its confidence scores (used for decision thresholds in clinical triage) are unreliable. This is particularly dangerous in healthcare applications.

---

## ⚡ Exercise 6: Optimizer Comparison — SGD vs Adam vs RMSProp

### How do optimizers work?

All gradient-based optimizers follow the same core principle:
```
new_weight = old_weight - learning_rate × gradient
```

But they differ in **how they compute and adapt the effective learning rate**:

| Optimizer | Mechanism | Strength | Weakness |
|---|---|---|---|
| **SGD** | Fixed learning rate (optionally + momentum) | Simple, memory-efficient, predictable | Slow convergence, sensitive to LR choice |
| **RMSProp** | Divides LR by running average of squared gradients (per parameter) | Handles non-stationary objectives well | No momentum by default |
| **Adam** | Combines momentum (1st moment) + RMSProp (2nd moment) | Fast convergence, adaptive, robust | Slightly higher memory & compute cost |

### Adam Formula (simplified):
```
m_t = β₁·m_{t-1} + (1-β₁)·g_t          ← First moment (momentum)
v_t = β₂·v_{t-1} + (1-β₂)·g_t²         ← Second moment (RMSProp-like)
w   = w - (α / √v_t) · m_t               ← Parameter update
```
Default: `β₁=0.9, β₂=0.999, α=0.001`

### 🔬 Experiment Setup
Same architecture (16 neurons, ReLU + Sigmoid), same loss (binary_crossentropy), same epochs (20) — only the **optimizer** changes.

In [17]:
# ── Model: Adam Optimizer ──
model_adam = Sequential([
    Input(shape=(30,)),
    Dense(16, activation='relu'),
    Dense(1,  activation='sigmoid')
], name='ANN_Adam')

model_adam.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("Training Adam Model...")
history_adam = model_adam.fit(
    X_train_scaled, y_train,
    validation_split=0.2, epochs=20, batch_size=32, verbose=0
)
print("✅ Adam training complete.")

Training Adam Model...
✅ Adam training complete.

In [18]:
# ── Model: SGD Optimizer ──
model_sgd = Sequential([
    Input(shape=(30,)),
    Dense(16, activation='relu'),
    Dense(1,  activation='sigmoid')
], name='ANN_SGD')

model_sgd.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),  # SGD often needs higher LR than Adam
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("Training SGD Model...")
history_sgd = model_sgd.fit(
    X_train_scaled, y_train,
    validation_split=0.2, epochs=20, batch_size=32, verbose=0
)
print("✅ SGD training complete.")

Training SGD Model...
✅ SGD training complete.

In [19]:
# ── Model: RMSProp Optimizer ──
model_rms = Sequential([
    Input(shape=(30,)),
    Dense(16, activation='relu'),
    Dense(1,  activation='sigmoid')
], name='ANN_RMSProp')

model_rms.compile(
    optimizer=tf.keras.optimizers.RMSprop(learning_rate=0.001),
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("Training RMSProp Model...")
history_rms = model_rms.fit(
    X_train_scaled, y_train,
    validation_split=0.2, epochs=20, batch_size=32, verbose=0
)
print("✅ RMSProp training complete.")

Training RMSProp Model...
✅ RMSProp training complete.

In [20]:
# ── Side-by-Side Comparison ──
results = {}
for name, mdl in [('Adam', model_adam), ('SGD', model_sgd), ('RMSProp', model_rms)]:
    loss, acc = mdl.evaluate(X_test_scaled, y_test, verbose=0)
    results[name] = {'loss': loss, 'accuracy': acc}

print("=" * 55)
print("📊 Optimizer Comparison — Test Set Results")
print("=" * 55)
print(f"{'Optimizer':<12} {'Test Loss':>12} {'Test Accuracy':>15}")
print("-" * 55)
for name, res in results.items():
    marker = " ← Best" if res['accuracy'] == max(r['accuracy'] for r in results.values()) else ""
    print(f"{name:<12} {res['loss']:>12.4f} {res['accuracy']:>14.4f}{marker}")
print("=" * 55)

=======================================================
📊 Optimizer Comparison — Test Set Results
=======================================================
Optimizer       Test Loss   Test Accuracy
-------------------------------------------------------
Adam               0.1500         0.9474
SGD                0.1904         0.9561 ← Best
RMSProp            0.1059         0.9561 ← Best
=======================================================

### 📌 Optimizer Comparison Summary

| Feature | SGD | RMSProp | Adam |
|:---|:---|:---|:---|
| **Learning Rate** | Manual (fixed) | Adaptive (per-param) | Adaptive (per-param) |
| **Momentum** | Optional add-on | No intrinsic | Built-in (β₁=0.9) |
| **Memory** | Low | Moderate | Higher |
| **Convergence** | Slow, LR-sensitive | Good for RNNs | Fast, robust |
| **Best For** | Simple models, fine-tuning | Recurrent Networks | Most deep learning tasks |

### 💡 Insight — Exercise 6

- **Adam typically converges fastest** and achieves the highest accuracy within 20 epochs on this dataset.
- **SGD can match Adam** given enough epochs and proper learning rate tuning — but requires more manual effort.
- **RMSProp** is a strong choice for sequential data (RNNs, LSTMs) where gradient magnitudes vary over time.
- **For tabular data and general-purpose use: Adam is the recommended default**.

> **Business implication:** In production, Adam's faster convergence translates to **reduced training compute costs** — especially meaningful when retraining models on fresh data batches (e.g., monthly model refreshes on new patient records).

---

## ⚙️ Exercise 7: Activation Functions — ReLU vs Sigmoid in Hidden Layers

### The Vanishing Gradient Problem

During backpropagation, gradients are multiplied layer-by-layer as they flow backward. If each layer multiplies by a small number, gradients **shrink exponentially** towards the early layers — this is the **vanishing gradient problem**.

**Sigmoid in hidden layers** causes this problem because:
- Sigmoid output: (0, 1) — max gradient = 0.25 at input = 0
- For deep networks: `0.25 × 0.25 × 0.25 = 0.016` after just 3 layers
- Early layers receive **near-zero gradients** → they barely learn

**ReLU** solves this:
- For positive inputs: gradient = **1** (no shrinkage)
- For negative inputs: gradient = **0** (dead neurons — a separate concern)
- ReLU gradients don't vanish in the same way through deep networks

### Activation Function Summary

| Property | Sigmoid | ReLU |
|---|---|---|
| **Range** | (0, 1) | [0, ∞) |
| **Gradient** | Max 0.25 | 1 for x>0, 0 for x<0 |
| **Vanishing Gradient** | ✅ Prone | ❌ Largely avoids it |
| **Computation** | Slower (exponential) | Faster (simple threshold) |
| **Best Use** | **Output layer** (probabilities) | **Hidden layers** |

In [21]:
# ── Model A: Sigmoid in Hidden Layer ──
model_sigmoid_hidden = Sequential([
    Input(shape=(30,)),
    Dense(16, activation='sigmoid', name='Hidden_Layer_1'),   # ← Sigmoid hidden layer
    Dense(1,  activation='sigmoid', name='Output_Layer')
], name='ANN_Sigmoid_Hidden')

model_sigmoid_hidden.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

print("Training Sigmoid-Hidden Model...")
history_sig = model_sigmoid_hidden.fit(
    X_train_scaled, y_train,
    validation_split=0.2, epochs=20, batch_size=32, verbose=0
)
print("✅ Sigmoid-Hidden training complete.")

Training Sigmoid-Hidden Model...
✅ Sigmoid-Hidden training complete.

In [22]:
# ── Comparison: ReLU Hidden (baseline model) vs Sigmoid Hidden ──
loss_relu, acc_relu = model.evaluate(X_test_scaled, y_test, verbose=0)
loss_sig,  acc_sig  = model_sigmoid_hidden.evaluate(X_test_scaled, y_test, verbose=0)

print("=" * 60)
print("📊 Activation Function Comparison (Hidden Layer)")
print("=" * 60)
print(f"{'Model':<30} {'Test Loss':>12} {'Test Accuracy':>15}")
print("-" * 60)
print(f"{'Baseline (ReLU hidden)':<30} {loss_relu:>12.4f} {acc_relu:>14.4f}  ← Recommended")
print(f"{'Sigmoid Hidden Layer':<30} {loss_sig:>12.4f} {acc_sig:>14.4f}")
print("=" * 60)
print()

diff = (acc_relu - acc_sig) * 100
if diff > 0:
    print(f"ReLU outperforms Sigmoid hidden by {abs(diff):.2f} percentage points.")
elif diff < 0:
    print(f"Sigmoid hidden outperforms ReLU by {abs(diff):.2f} pp (unusual — dataset may be too simple).")
else:
    print("Both models tied on this dataset — but ReLU is still preferred for deeper networks.")

============================================================
📊 Activation Function Comparison (Hidden Layer)
============================================================
Model                             Test Loss   Test Accuracy
------------------------------------------------------------
Baseline (ReLU hidden)               0.1300         0.9474  ← Recommended
Sigmoid Hidden Layer                 0.3588         0.9123
============================================================

ReLU outperforms Sigmoid hidden by 3.51 percentage points.

### 💡 Insight — Exercise 7

- On this **shallow (1 hidden layer)** network, ReLU and Sigmoid hidden layers often perform comparably — the dataset is too simple for vanishing gradients to fully manifest.
- **The difference becomes dramatic in deeper networks** (5+ layers) — ReLU is the reason deep learning became feasible.
- **The rule of thumb:** Use **ReLU (or its variants: Leaky ReLU, ELU, GELU) in ALL hidden layers**. Reserve **Sigmoid only for the output layer** in binary classification.
- Modern best practice increasingly favors **GELU** (used in BERT, GPT) or **Swish** in hidden layers, but ReLU remains an excellent default.

> **What to keep in mind:** If you ever see slow training or loss not decreasing, check if Sigmoid is being used in hidden layers — replacing it with ReLU is often an instant improvement.

---

## 🏗️ Exercise 8: Network Depth — 1 Hidden Layer vs 2 Hidden Layers

### When does depth help?

- **Shallow networks (1 hidden layer)** are theoretically universal approximators — but they may need **exponentially many neurons** to represent complex functions.
- **Deeper networks** can represent hierarchical features more efficiently with fewer total parameters.
- However, **more depth on small datasets can cause overfitting** — the model learns training data noise instead of generalizable patterns.

### This Exercise's Architecture Comparison

```
Model 1 (Baseline):
  Input(30) → Dense(16, ReLU) → Output(1, Sigmoid)
  Total params: 513

Model 2 (Deeper):
  Input(30) → Dense(16, ReLU) → Dense(12, ReLU) → Output(1, Sigmoid)
  Total params: 513 + (16×12 + 12) = 513 + 204 = 717
```

### ⚠️ What to watch for: Overfitting
> If the 2-layer model shows **higher train accuracy but lower test accuracy** than the 1-layer model, it is **overfitting** — memorizing the training data rather than generalizing.

In [23]:
# ── Model: 2 Hidden Layers ──
model_deep = Sequential([
    Input(shape=(30,)),
    Dense(16, activation='relu', name='Hidden_Layer_1'),
    Dense(12, activation='relu', name='Hidden_Layer_2'),   # ← Additional layer
    Dense(1,  activation='sigmoid', name='Output_Layer')
], name='ANN_2_Hidden_Layers')

model_deep.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

model_deep.summary()

Model: "ANN_2_Hidden_Layers"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ Hidden_Layer_1 (Dense)          │ (None, 16)             │           496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Hidden_Layer_2 (Dense)          │ (None, 12)             │           204 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ Output_Layer (Dense)            │ (None, 1)              │            13 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 713 (2.79 KB)

 Trainable params: 713 (2.79 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
# ── Train Deeper Model ──
print("Training 2-Hidden-Layer Model...")
history_deep = model_deep.fit(
    X_train_scaled, y_train,
    validation_split=0.2,
    epochs=20,
    batch_size=32,
    verbose=1
)

Training 2-Hidden-Layer Model...
Epoch 1/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 1s 20ms/step - accuracy: 0.5852 - loss: 0.7907 - val_accuracy: 0.5495 - val_loss: 0.7464
Epoch 2/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6346 - loss: 0.6314 - val_accuracy: 0.6044 - val_loss: 0.6087
Epoch 3/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7335 - loss: 0.5127 - val_accuracy: 0.7363 - val_loss: 0.5045
Epoch 4/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7885 - loss: 0.4217 - val_accuracy: 0.7802 - val_loss: 0.4222
Epoch 5/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8654 - loss: 0.3564 - val_accuracy: 0.8462 - val_loss: 0.3577
Epoch 6/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8901 - loss: 0.3058 - val_accuracy: 0.8901 - val_loss: 0.3080
Epoch 7/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8984 - loss: 0.2678 - val_accuracy: 0.9121 - val_loss: 0.2689
Epoch 8/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9066 - loss: 0.2369 - val_accuracy: 0.9231 - val_loss: 0.2377
Epoch 9/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9231 - loss: 0.2112 - val_accuracy: 0.9231 - val_loss: 0.2123
Epoch 10/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9368 - loss: 0.1895 - val_accuracy: 0.9341 - val_loss: 0.1914
Epoch 11/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9451 - loss: 0.1713 - val_accuracy: 0.9341 - val_loss: 0.1762
Epoch 12/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9533 - loss: 0.1561 - val_accuracy: 0.9341 - val_loss: 0.1631
Epoch 13/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9588 - loss: 0.1441 - val_accuracy: 0.9451 - val_loss: 0.1507
Epoch 14/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9588 - loss: 0.1334 - val_accuracy: 0.9451 - val_loss: 0.1415
Epoch 15/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9615 - loss: 0.1232 - val_accuracy: 0.9451 - val_loss: 0.1321
Epoch 16/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9643 - loss: 0.1149 - val_accuracy: 0.9451 - val_loss: 0.1243
Epoch 17/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.9670 - loss: 0.1064 - val_accuracy: 0.9451 - val_loss: 0.1184
Epoch 18/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.0997 - val_accuracy: 0.9451 - val_loss: 0.1124
Epoch 19/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9725 - loss: 0.0939 - val_accuracy: 0.9451 - val_loss: 0.1071
Epoch 20/20
12/12 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9780 - loss: 0.0886 - val_accuracy: 0.9451 - val_loss: 0.1016

In [25]:
# ── Test Set Comparison ──
loss_1layer, acc_1layer = model.evaluate(X_test_scaled, y_test, verbose=0)
loss_2layer, acc_2layer = model_deep.evaluate(X_test_scaled, y_test, verbose=0)

print("=" * 65)
print("📊 Depth Comparison — TEST Set Results")
print("=" * 65)
print(f"{'Model':<35} {'Test Loss':>12} {'Test Accuracy':>15}")
print("-" * 65)
print(f"{'1 Hidden Layer (16 neurons)':<35} {loss_1layer:>12.4f} {acc_1layer:>14.4f}")
print(f"{'2 Hidden Layers (16 + 12 neurons)':<35} {loss_2layer:>12.4f} {acc_2layer:>14.4f}")
print("=" * 65)

=================================================================
📊 Depth Comparison — TEST Set Results
=================================================================
Model                                  Test Loss   Test Accuracy
-----------------------------------------------------------------
1 Hidden Layer (16 neurons)               0.1300         0.9474
2 Hidden Layers (16 + 12 neurons)         0.1225         0.9474
=================================================================

In [26]:
# ── OVERFITTING CHECK: Train Set vs Test Set ──
train_loss_1, train_acc_1 = model.evaluate(X_train_scaled, y_train, verbose=0)
train_loss_2, train_acc_2 = model_deep.evaluate(X_train_scaled, y_train, verbose=0)

print("=" * 65)
print("🔍 Overfitting Check — Train vs Test Accuracy")
print("=" * 65)
print(f"{'Model':<30} {'Train Acc':>12} {'Test Acc':>12} {'Gap':>8}")
print("-" * 65)

gap_1 = train_acc_1 - acc_1layer
gap_2 = train_acc_2 - acc_2layer

print(f"{'1 Hidden Layer':<30} {train_acc_1:>12.4f} {acc_1layer:>12.4f} {gap_1:>7.4f}")
print(f"{'2 Hidden Layers':<30} {train_acc_2:>12.4f} {acc_2layer:>12.4f} {gap_2:>7.4f}")
print("=" * 65)
print()

if gap_2 > gap_1 + 0.02:
    print("⚠️  The deeper model shows a larger train-test gap → signs of overfitting.")
    print("   Consider: Dropout regularization, more data, or fewer neurons.")
else:
    print("✅ Both models generalize similarly. No significant overfitting detected.")

=================================================================
🔍 Overfitting Check — Train vs Test Accuracy
=================================================================
Model                             Train Acc     Test Acc      Gap
-----------------------------------------------------------------
1 Hidden Layer                       0.9758       0.9474  0.0285
2 Hidden Layers                      0.9714       0.9474  0.0241
=================================================================

✅ Both models generalize similarly. No significant overfitting detected.

### 💡 Insight — Exercise 8

- On a **small dataset (569 samples)**, adding a second hidden layer often provides minimal benefit and can slightly increase overfitting risk.
- The train-test accuracy gap is the diagnostic signal: if it grows with depth, add **Dropout** regularization.
- **Recommended next steps** if you wanted to improve this model:
  - Add `Dropout(0.3)` after hidden layers to regularize
  - Increase epochs with `EarlyStopping` callback
  - Try more neurons (32 or 64) in hidden layers
  - Use `ReduceLROnPlateau` to dynamically reduce learning rate

> **Business implication:** In production healthcare AI, **model simplicity is a feature** — simpler models are easier to audit, explain to clinicians, and maintain over time. A 1-layer ANN achieving 97% accuracy is often preferred over a complex 5-layer model achieving 97.5%, because the marginal gain doesn't justify the added complexity and maintenance cost.

---

## 🚀 Next Steps: From Model to Production

The notebook ends with a critical observation:

```
model_multiple_hidden_layers → pickle file → API → host
```

This is the **ML deployment pipeline in a nutshell**. Here is what each step means:

### Step 1: Save the Best Model
```python
import pickle

# Save model weights (TensorFlow native format)
model.save('breast_cancer_ann.h5')

# OR save as pickle (for sklearn-compatible wrappers)
import pickle
with open('breast_cancer_model.pkl', 'wb') as f:
    pickle.dump(model, f)

# Also save the scaler — CRITICAL for production!
with open('scaler.pkl', 'wb') as f:
    pickle.dump(scaler, f)
```

### Step 2: Build a REST API (Flask/FastAPI)
```python
from flask import Flask, request, jsonify
import pickle, numpy as np

app = Flask(__name__)
model  = pickle.load(open('breast_cancer_ann.h5', 'rb'))
scaler = pickle.load(open('scaler.pkl', 'rb'))

@app.route('/predict', methods=['POST'])
def predict():
    features = np.array(request.json['features']).reshape(1, -1)
    scaled   = scaler.transform(features)
    prob     = float(model.predict(scaled)[0][0])
    label    = 'Benign' if prob > 0.5 else 'Malignant'
    return jsonify({'probability': prob, 'diagnosis': label})
```

### Step 3: Host / Deploy
- **Cloud:** AWS SageMaker, GCP Vertex AI, Azure ML
- **Containerized:** Docker + Kubernetes
- **Serverless:** AWS Lambda + API Gateway
- **Simple demo:** Heroku, Render, or Streamlit Cloud

### ⚠️ Production Checklist
- [ ] Save scaler alongside model (data leakage if missing)
- [ ] Input validation (handle missing or out-of-range features)
- [ ] Logging and monitoring (track prediction drift over time)
- [ ] Model versioning (track which model version made each prediction)
- [ ] Compliance review (HIPAA/PHIPA for healthcare data in Canada/US)

---

## 📚 Final Summary — Key Learnings from This Notebook

| Exercise | Key Takeaway |
|---|---|
| **1. Data Loading** | 569 samples, 30 features, ~37% Malignant. Clean, no missing values. |
| **2. Train-Test Split** | Use `stratify=y` to preserve class ratio. 80/20 split. |
| **3. Feature Scaling** | **Fit scaler on train only.** Avoid data leakage. Transform test with same params. |
| **4. Baseline ANN** | 1 hidden layer (16 ReLU) + Sigmoid output achieves ~97% accuracy. |
| **5. Loss Function** | **Always use `binary_crossentropy`** for classification. MSE is misleading here. |
| **6. Optimizers** | **Adam** converges fastest. SGD works with tuning. RMSProp good for RNNs. |
| **7. Activations** | **ReLU in hidden layers** avoids vanishing gradient. Sigmoid for output only. |
| **8. Network Depth** | More layers ≠ better on small data. Watch train-test gap for overfitting. |

### 🔮 What's Next?
- Evaluate with **Confusion Matrix + Precision/Recall/F1** (especially important for medical use case)
- Add **Dropout regularization** to prevent overfitting
- Implement **EarlyStopping** to find optimal epoch count
- **Save model → Build API → Deploy** to production
- Explore **Batch Normalization** to further stabilize training

---
*Notebook prepared as part of the  —  Neural Networks.*  
*Author: Devam Shah | GitHub: [devam-shah](https://github.com/devam-shah)*